oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token-url: https://oauth2.googleapis.com/token
    user-info-url: https://www.googleapis.com/userinfo/v2/me
    redirect-uri: http://localhost:8080/login/oauth2/code/google
    delete-account-url: http://localhost:8080/api/delete-google-account
  apple:
    ios:
      client-id: ${APPLE_IOS_CLIENT_ID}
      team-id: ${APPLE_IOS_TEAM_ID}
      key-id: ${APPLE_IOS_KEY_ID}
      private-key: ${APPLE_IOS_PRIVATE_KEY}
      token-url: ${APPLE_IOS_TOKEN_URL}
      delete-account-url: ${APPLE_IOS_DELETE_ACCOUNT_URL}


jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time: 3600000
  refresh-token-expire-time: 5184000000


# UserDetailsService 빈 자동등록을 해제하여 자동으로 생성되는 보안 비밀번호와 관련된 경고 메시지가 표시되지 않도록 한다.
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  config:
    import: "optional:file:.env[.properties]"
